development:
  adapter: postgresql
  database: bionatural_dev
  pool: 5
  timeout: 5000
  username: bionatural
  password: bi0n1tura1
test:
  adapter: postgresql
  database: bionatural_test
  pool: 5
  timeout: 5000
  username: bionatural
  password: bi0n1tura1

# production setting are not required on Heroku